name: Publish rolling build
on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ${{ matrix.os }}

    permissions:
      packages: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        arch: ["amd64"]
        include:
          - arch: amd64
            os: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set image identity
      id: image_id
      run: echo ::set-output name=ID::${GITHUB_REPOSITORY,,}

    - name: Publish to GitHub Container Registry
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/${{ matrix.arch }}
        push: true
        tags: |
          ghcr.io/${{ steps.image_id.outputs.ID }}:latest